# Generated by Django 6.0.3 on 2026-03-12 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('origen', models.CharField(choices=[('IG', 'Instagram'), ('TK', 'TikTok'), ('WB', 'Web'), ('RE', 'Referido')], default='WB', max_length=2)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado'), ('PERDIDO', 'Perdido'), ('CERRADO', 'Venta Cerrada')], default='NUEVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('asignado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('prospecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='ventas.prospecto')),
            ],
        ),
    ]
